---
- name: Install pagekite
  ansible.builtin.apt:
    pkg: pagekite
    update_cache: true
    cache_valid_time: 3600

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Copy logcheck rules
  ansible.builtin.copy:
    src: debian-11-logcheck-mit-pagekite
    dest: /etc/logcheck/ignore.d.server/mit-pagekite
    mode: "0644"
  when: "'logcheck' in ansible_facts.packages"
